version: '3.7'
services:
  web:
    container_name: tagzapp.web
    hostname: tagzappweb
    build:
      dockerfile: ./src/TagzApp.Web/dockerfile
      context: .
    ports:
      - "80" # runs on a random local port. Change to "8080:80" if you want to run on localhost:8080

    # environment:
    # - providers:mastodon:BaseAddress=https://example.com
    # - providers:youtube:ApiKey=
    # - providers:twitter:DefaultHeaders:Authorization=Bearer $TOKEN
    # - providers:twitter:ApiKey=
    # - providers:twitter:ApiSecretKey=
    # - providers:twitter:AccessToken=
    # - providers:twitter:AccessTokenSecret=
