{
 "title": "TagzApp Dashboard",
 "description": "TagzApp monitoring and metrics.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">TagzApp Dashboard</h1>\n<section style=\"text-align: center\">\n<img src=\"https://raw.githubusercontent.com/FritzAndFriends/TagzApp/main/doc/img/tagzapp.png\" alt=\"TagzApp Logo\" />\n</section>"
   }
  },
  {
   "title": "Top 5 Twitch Chatters",
   "type": "bargauge",
   "description": "Top 5 Twitch Chatters",
   "gridPos": { "h": 11, "w": 8, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (author) (sort_desc(max_over_time(messages_received_message_total{provider=\"twitchchat\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Posters",
   "type": "bargauge",
   "description": "Top 5 posters across all providers",
   "gridPos": { "h": 11, "w": 8, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (author) (sort_desc(max_over_time(messages_received_message_total[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TwitchChat Messages Received",
   "type": "timeseries",
   "description": "Posts received across all providers.",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "round(increase(messages_received_message_total{provider=\"twitchchat\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}